huggingface:
  model: "meta-llama/Llama-2-70b-chat-hf"
  revision: "e9149a12809580e8602995856f8098ce973d1080"
  download: true
djl:
  engine: "Python"
  option.entryPoint: "djl_python.transformers_neuronx"
  option.tensor_parallel_degree: 24
  option.amp: "f16"
  option.n_positions: 2048
  option.model_loading_timeout: 3600
  option.model_loader: "tnx"
sagemaker:
  model:
    name: "llama-2-70b-chat-hf-transformers-neuronx"
    container: "containers/pytorch-inf2"
    env: 
      HUGGINGFACE_HUB_CACHE: "/tmp"
      TRANSFORMERS_CACHE: "/tmp"
  endpoint:
    name: "llama-2-70b-chat-hf-transformers-neuronx"
    instance_type: "ml.inf2.48xlarge"
    initial_instance_count: 1
    variant_name: "test"
    model_data_download_timeout_secs: 3600
    container_startup_health_check_timeout_secs: 3600
    volume_size_gb: 500
test:
  module_name: "prompt_generator"
  module_dir: "modules/inst-semeval2017"
  prompt_generator: "PromptGenerator"
  params: { "do_sample": true, "max_new_tokens": 1024, "top_k": 50 }
  warmup_iters: 1
  max_iters: 10
  output_dir: "output/llama-2-70b-chat-hf/transformers-neuronx"