name: MLF PR Build (ap-east-1)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configures AWS creds
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MLF_ap_east_1_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MLF_ap_east_1_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - name: Download Testing Tool
        run: |
          aws s3 cp s3://sagemaker-mead-cli/mead-nb-test.tar.gz mead-nb-test.tar.gz
          tar -xzf mead-nb-test.tar.gz

      - name: Run Notebook Tests
        run: |
          export JAVA_HOME=$(get-java-home)
          echo "set JAVA_HOME=$JAVA_HOME"
          export SAGEMAKER_ROLE_ARN=$(aws iam list-roles --output text --query "Roles[?RoleName == 'SageMakerRole'].Arn")
          echo "set SAGEMAKER_ROLE_ARN=$SAGEMAKER_ROLE_ARN"
          ./runtime/bin/mead-run-nb-test \
          --instance-type ml.c4.8xlarge \
          --region ap-east-1 \
          --lifecycle-config-name install-python-sdk \
          --notebook-instance-role-arn $SAGEMAKER_ROLE_ARN \
          ./advanced_functionality/kmeans_bring_your_own_model/kmeans_bring_your_own_model.ipynb \
          ./advanced_functionality/tensorflow_iris_byom/tensorflow_BYOM_iris.ipynb \
          ./sagemaker-python-sdk/1P_kmeans_highlevel/kmeans_mnist.ipynb \
          ./sagemaker-python-sdk/managed_spot_training_mxnet/managed_spot_training_mxnet.ipynb \
          ./sagemaker-python-sdk/managed_spot_training_tensorflow_estimator/managed_spot_training_tensorflow_estimator.ipynb \
          ./sagemaker-python-sdk/mxnet_onnx_eia/mxnet_onnx_eia.ipynb \
          ./sagemaker-python-sdk/mxnet_onnx_export/mxnet_onnx_export.ipynb \
          ./sagemaker-python-sdk/phubytorch_cnn_cifar10/pytorch_local_mode_cifar10.ipynb \
          ./sagemaker-python-sdk/scikit_learn_randomforest/Sklearn_on_SageMaker_end2end.ipynb \
          ./sagemaker-python-sdk/tensorflow_moving_from_framework_mode_to_script_mode/tensorflow_moving_from_framework_mode_to_script_mode.ipynb \
          ./sagemaker-python-sdk/tensorflow_script_mode_pipe_mode/tensorflow_script_mode_pipe_mode.ipynb \
          ./sagemaker-python-sdk/tensorflow_script_mode_using_shell_commands/tensorflow_script_mode_using_shell_commands.ipynb \
          ./sagemaker-python-sdk/tensorflow_serving_container/tensorflow_serving_container.ipynb \
          ./sagemaker-python-sdk/tensorflow_serving_using_elastic_inference_with_your_own_model/tensorflow_serving_pretrained_model_elastic_inference.ipynb
